### ISSUE TITLE
Add Circular Progress Components

### ISSUE THREAD

**Issue by dudupopkhadze** [dudupopkhadze/Android-Showcase#13]
There are some progress libraries in app, but i think  adding this one will be very useful for many developers/designers.

You can find this Library [here](https://github.com/lzyzsd/CircleProgress)

There is no need to add same components with different sizes, just add unique ones.

Adding new progress component guidline:

![image](https://user-images.githubusercontent.com/48488310/88458919-5982f580-cea2-11ea-8926-f35d6c11c4cc.png)

This List is locadet at data/LibariesInfo.kt, add "CircularProgress" in this list.

![image](https://user-images.githubusercontent.com/48488310/88458907-4e2fca00-cea2-11ea-873a-ae6f4cea513d.png)

Then map "CircularProgress" with your ActivityClass, whitch should implement our ComponentActivity Interface.
After this, your component will appear in Progress Components page and with clicking "Circular Progress" your activiry should start.

Rest is up to you.

**Comment by shoniavika** [comment]
I'll take this one

**Comment by dudupopkhadze** [comment]
deprecated library
