### ISSUE TITLE
Add Android Circle Image View

### ISSUE THREAD

**Issue by shotanozadze** [dudupopkhadze/Android-Showcase#21]
You can find this Library [here](https://github.com/hdodenhof/CircleImageView).

There is no need to add same components with different sizes, just add unique ones.

There is no image library at this point in our app, so you should add new libraries list.

![image](https://user-images.githubusercontent.com/48485182/88462244-0ec1a780-cebb-11ea-84c2-e57ed7fafc8b.png)

Add "Image" in this list and it will appear in app main menu. Then create new list which will contain different image libraries and components. Last but not least map your added activity to component name bewlow and you are ready to go.

![image](https://user-images.githubusercontent.com/48485182/88462248-15501f00-cebb-11ea-849a-a4dc8463a8a8.png)

Ask for help anytime.

**Comment by Gogotchuri** [comment]
I would like to help with that.
